[package]
name = "last_kingdom"
version = "0.1.0"
edition = "2021"

[dependencies]
# bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "latest" , features = ["dynamic"]}

bevy = { version = "0.6.1" }
bevy_asset_loader = "0.8"
rand = "0.8.3"
bevy-inspector-egui = "0.8"

bevy_mod_debugdump= "0.3.0"
bevy_kira_audio = { version = "0.8" }




[dependencies.bevy_asset_loader_derive]
version = "0.8"
default-features = false
features = ["render"]



[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

#[profile.release]
#lto = "thin"
#codegen-units = 1

