# brace_style = "AlwaysNextLine"
# control_brace_style = "AlwaysNextLine"
# fn_args_layout = "Compressed"

tab_spaces = 4
max_width = 120
struct_lit_width = 100
chain_width = 100
use_field_init_shorthand = true
newline_style = "Unix"
